# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.1
MAINTAINER qianlnk(qianlnk@163.com)

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
